# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhiHuDaily' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhiHuDaily
	pod 'Masonry'
	pod 'AFNetworking'
	pod 'MJRefresh'
  target 'ZhiHuDailyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZhiHuDailyUITests' do
    # Pods for testing
  end

end
